"""
Report Generation Module
This module handles the creation of comprehensive reports from the cleaning process.
"""

def generate_report(before: dict, after: dict, cleaning_report: dict, execution_time: float) -> dict:
    """
    Generate a structured report from the cleaning process results.

    Args:
        before (dict): Statistics and information about the data before cleaning.
                       Expected keys: 'rows', 'columns', etc.
        after (dict): Statistics and information about the data after cleaning.
                      Expected keys: 'rows', 'columns', etc.
        cleaning_report (dict): Report generated by the clean_data function.
                                Expected keys: 'duplicates_removed', 'missing_values_filled',
                                'operations', 'alerts', 'sample', 'summary', 'recommendations',
                                'column_conversions'.
        execution_time (float): Total time taken for the cleaning process in seconds.

    Returns:
        dict: A comprehensive report with all necessary fields for the frontend.
    """

    # ============================================
    # 1. استخراج الإحصائيات الأساسية
    # ============================================
    rows_before = before.get("rows", 0)
    rows_after = after.get("rows", 0)
    columns_before = before.get("columns", 0)
    columns_after = after.get("columns", 0)

    duplicates_removed = cleaning_report.get("duplicates_removed", 0)
    missing_values_filled = cleaning_report.get("missing_values_filled", 0)

    # ============================================
    # 2. بناء التقرير النهائي
    # ============================================
    report = {
        # ---- الإحصائيات الرئيسية (تُستخدم مباشرة في Frontend) ----
        "rows_before": rows_before,
        "rows_after": rows_after,
        "columns_before": columns_before,
        "columns_after": columns_after,
        "duplicates_removed": duplicates_removed,
        "missing_values_filled": missing_values_filled,
        "execution_time": execution_time,

        # ---- البيانات التفصيلية من عملية التنظيف ----
        "sample": cleaning_report.get("sample", []),  # عينة من البيانات المنظفة
        "alerts": cleaning_report.get("alerts", []),  # تنبيهات وتحذيرات
        "summary": cleaning_report.get(
            "summary",
            f"Cleaned {rows_before} rows. Removed {duplicates_removed} duplicates and filled {missing_values_filled} missing values."
        ),
        "operations": cleaning_report.get("operations", []),  # قائمة العمليات المنفذة
        "recommendations": cleaning_report.get("recommendations", []),  # توصيات للتحسين
        "column_conversions": cleaning_report.get("column_conversions", []),  # تحويلات الأعمدة

        # ---- البيانات الخام (للرجوع إليها في حال الحاجة) ----
        "before": before,
        "after": after,
        "cleaning_report": cleaning_report,
    }

    return report