"use client";

import { useCallback, useMemo, useRef, useState } from "react";
import {
  Play,
  Loader2,
  UploadCloud,
  Download,
  Database,
  FileCode,
  Copy,
  Save,
  Table2,
  Columns3,
  X,
  CheckCircle2,
  ChevronDown,
  ChevronRight,
  Server,
  FolderTree,
  Braces,
  GitBranch,
} from "lucide-react";
import Papa from "papaparse";
import ExcelJS from "exceljs";
import { useDataLink, UseLinkedData, type LinkedDataset } from "./data-link";
import { rememberProject, rememberAction } from "@/lib/learning-store";

const KEYWORDS =
  /\b(SELECT|FROM|WHERE|GROUP\s+BY|ORDER\s+BY|HAVING|LIMIT|OFFSET|JOIN|LEFT|RIGHT|INNER|OUTER|ON|AS|AND|OR|NOT|IN|BETWEEN|LIKE|IS|NULL|DISTINCT|COUNT|SUM|AVG|MIN|MAX|NVL|IFNULL|COALESCE|ALTER|CREATE|DROP|INSERT|UPDATE|DELETE|TABLE|INDEX|PRIMARY|KEY|REFERENCES|CASE|WHEN|THEN|ELSE|END|UNION|ALL|EXISTS|ASC|DESC|INTO|VALUES|SET|DATABASE|USE|TRUNCATE|VIEW|INT|VARCHAR|TEXT|NUMERIC|DECIMAL|REAL|BOOLEAN|TIMESTAMP|DATE|BIGINT)\b/i;
const STRING_RE = /('(?:[^'\\]|\\.)*'|"(?:[^"\\]|\\.)*")/;
const NUMBER_RE = /\b\d+(?:\.\d+)?\b/;

/* ─── SQL Syntax Highlighter ─── */
function highlightSql(sql: string): React.ReactNode[] {
  const tokens: React.ReactNode[] = [];
  let rest = sql;
  let key = 0;

  // Extract comments first
  const parts: { type: "comment" | "code"; text: string }[] = [];
  let lastIdx = 0;
  const commentRegex = /(--[^\n]*|\/\*[\s\S]*?\*\/)/g;
  let m: RegExpExecArray | null;
  while ((m = commentRegex.exec(rest)) !== null) {
    if (m.index > lastIdx)
      parts.push({ type: "code", text: rest.substring(lastIdx, m.index) });
    parts.push({ type: "comment", text: m[0] });
    lastIdx = m.index + m[0].length;
  }
  if (lastIdx < rest.length)
    parts.push({ type: "code", text: rest.substring(lastIdx) });

  const codeStyle = (txt: string): React.ReactNode[] => {
    const out: React.ReactNode[] = [];
    // Split by strings and identify keywords/numbers
    const segments = txt.split(STRING_RE);
    for (let i = 0; i < segments.length; i++) {
      const seg = segments[i];
      if (!seg) continue;
      if (i % 2 === 1) {
        out.push(
          <span key={key++} className="text-emerald-300">
            "{seg}"
          </span>,
        );
        continue;
      }
      const numSegs = seg.split(NUMBER_RE);
      for (let j = 0; j < numSegs.length; j++) {
        if (!numSegs[j]) continue;
        if (j % 2 === 1) {
          out.push(
            <span key={key++} className="text-amber-300">
              {numSegs[j]}
            </span>,
          );
          continue;
        }
        const kwSegs = numSegs[j].split(KEYWORDS);
        for (let k = 0; k < kwSegs.length; k++) {
          if (!kwSegs[k]) continue;
          if (k % 2 === 1) {
            out.push(
              <span key={key++} className="text-[#4f7cff] font-semibold">
                {kwSegs[k]}
              </span>,
            );
          } else {
            out.push(<span key={key++}>{kwSegs[k]}</span>);
          }
        }
      }
    }
    return out;
  };

  for (const p of parts) {
    if (p.type === "comment") {
      tokens.push(
        <span key={key++} className="text-white/25 italic">
          {p.text}
        </span>,
      );
    } else {
      tokens.push(<span key={key++}>{codeStyle(p.text)}</span>);
    }
  }
  return tokens;
}

/* ─── helpers ─── */
function dlBlob(blob: Blob, name: string) {
  const u = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = u;
  a.download = name;
  document.body.appendChild(a);
  a.click();
  a.remove();
  URL.revokeObjectURL(u);
}
function dlStr(
  content: string,
  name: string,
  mime = "text/plain;charset=utf-8",
) {
  dlBlob(new Blob([content], { type: mime }), name);
}

function detectSqlType(rows: Record<string, unknown>[], col: string): string {
  const vals = rows
    .slice(0, 100)
    .map((r) => r[col])
    .filter((v) => v != null && v !== "");
  if (vals.length === 0) return "TEXT";
  const allNum = vals.every((v) => !Number.isNaN(Number(v)));
  const allBool = vals.every(
    (v) =>
      String(v).toLowerCase() === "true" ||
      String(v).toLowerCase() === "false" ||
      String(v) === "1" ||
      String(v) === "0",
  );
  const allDate = vals.every((v) => !Number.isNaN(Date.parse(String(v))));
  if (allBool) return "BOOLEAN";
  if (allDate) return "TIMESTAMP";
  if (allNum) return "NUMERIC(18,4)";
  return "VARCHAR(255)";
}

function makeCreateTable(
  name: string,
  headers: string[],
  rows: Record<string, unknown>[],
): string {
  let sql = `-- Auto-generated by OQZARO SQL Designer\n`;
  sql += `IF OBJECT_ID(N'dbo.${name}', N'U') IS NOT NULL DROP TABLE dbo.${name};\nGO\n\n`;
  sql += `CREATE TABLE dbo.${name} (\n`;
  headers.forEach((h, i) => {
    const safe = h.replace(/[^\w\u0600-\u06FF]/g, "_");
    const type = detectSqlType(rows, h);
    sql += `\t[${safe}] ${type}${i < headers.length - 1 ? "," : ""}\n`;
  });
  sql += `);\nGO\n\n`;
  return sql;
}

function makeInsertSql(
  name: string,
  headers: string[],
  rows: Record<string, unknown>[],
  limit = 50,
): string {
  let sql = `INSERT INTO dbo.${name} (${headers.map((h) => `[${h.replace(/[^\w\u0600-\u06FF]/g, "_")}]`).join(", ")})\nVALUES\n`;
  const rowSqls = rows.slice(0, limit).map((r) => {
    const vals = headers.map((h) => {
      const v = r[h];
      if (v == null || v === "") return "NULL";
      if (!Number.isNaN(Number(v))) return String(v);
      return `N'${String(v).replace(/'/g, "''")}'`;
    });
    return `\t(${vals.join(", ")})`;
  });
  sql += rowSqls.join(",\n") + ";";
  return sql;
}

/* ═══════════════════════════════════════════════════════════════
   SQL VIEWER COMPONENT (SSMS-style)
   ═══════════════════════════════════════════════════════════════ */
interface SqlCommand {
  id: string;
  label: string;
  sql: string;
}

interface QueryResult {
  columns: string[];
  rows: Record<string, unknown>[];
  elapsedMs: number;
  rowCount: number;
}

const PRESET_QUERIES: SqlCommand[] = [
  { id: "q1", label: "كل البيانات", sql: "SELECT TOP 100 *\nFROM dbo.data;\n" },
  {
    id: "q2",
    label: "عدد الصفوف",
    sql: "SELECT COUNT(*) AS total_rows\nFROM dbo.data;\n",
  },
  { id: "q3", label: "أول 5 صفوف", sql: "SELECT TOP 5 *\nFROM dbo.data;\n" },
];

export function SqlViewer({
  onDataChange,
}: {
  onDataChange?: (data: {
    headers: string[];
    rows: Record<string, unknown>[];
    fileName: string;
  }) => void;
} = {}) {
  const inputRef = useRef<HTMLInputElement | null>(null);
  const { publish } = useDataLink();

  const [headers, setHeaders] = useState<string[]>([]);
  const [rows, setRows] = useState<Record<string, unknown>[]>([]);
  const [fileName, setFileName] = useState("");
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState("");
  const [query, setQuery] = useState("SELECT TOP 100 *\nFROM dbo.data;\n");
  const [result, setResult] = useState<QueryResult | null>(null);
  const [running, setRunning] = useState(false);
  const [tab, setTab] = useState<"query" | "schema" | "data">("query");
  const [objectExplorerOpen, setObjectExplorerOpen] = useState(true);
  const [schemaOpen, setSchemaOpen] = useState(true);

  // Query history
  const [history, setHistory] = useState<
    { time: string; query: string; status: "ok" | "error" }[]
  >([]);

  // ─── Load file ───
  const loadFile = useCallback(
    async (f: File | null) => {
      if (!f) return;
      setLoading(true);
      setError("");
      setResult(null);
      try {
        const ext = f.name.split(".").pop()?.toLowerCase() || "";
        if (ext === "csv") {
          const text = await f.text();
          const parsed = Papa.parse(text, {
            header: true,
            skipEmptyLines: true,
            dynamicTyping: false,
          });
          if (!parsed.meta.fields) throw new Error("bad");
          const h = parsed.meta.fields.filter(Boolean);
          const data = (parsed.data as Record<string, unknown>[]).map((r) => {
            const obj: Record<string, unknown> = {};
            for (const c of h) {
              const v = r[c];
              obj[c] = v === "" || v == null ? null : v;
            }
            return obj;
          });
          setHeaders(h);
          setRows(data);
          setFileName(f.name);
          onDataChange?.({ headers: h, rows: data, fileName: f.name });
          publish({ headers: h, rows: data, fileName: f.name, source: "sql" });
          rememberProject({ fileName: f.name, rows: data.length, headers: h });
          rememberAction(f.name, {
            type: "sql",
            detail: "loaded into SQL viewer",
            at: Date.now(),
          });
          setQuery(`SELECT TOP 100 *\nFROM dbo.data;\n`);
        } else {
          const buf = await f.arrayBuffer();
          const wb = new ExcelJS.Workbook();
          await wb.xlsx.load(buf);
          const ws = wb.worksheets[0];
          if (!ws) throw new Error("empty");
          const all: unknown[][] = [];
          ws.eachRow({ includeEmpty: false }, (row) =>
            all.push((row.values as unknown[]).slice(1)),
          );
          if (!all.length) throw new Error("empty");
          const h: string[] = [];
          all[0].forEach((c) => {
            const s = c == null ? "" : String(c).trim();
            if (s) h.push(s);
          });
          const data: Record<string, unknown>[] = [];
          for (const r of all.slice(1)) {
            const obj: Record<string, unknown> = {};
            h.forEach((col, idx) => {
              const v = r[idx] ?? null;
              obj[col] =
                v === "" ? null : typeof v === "object" ? JSON.stringify(v) : v;
            });
            data.push(obj);
          }
          setHeaders(h);
          setRows(data);
          setFileName(f.name);
          onDataChange?.({ headers: h, rows: data, fileName: f.name });
          publish({ headers: h, rows: data, fileName: f.name, source: "sql" });
          rememberProject({ fileName: f.name, rows: data.length, headers: h });
          rememberAction(f.name, {
            type: "sql",
            detail: "loaded into SQL viewer",
            at: Date.now(),
          });
          setQuery(`SELECT TOP 100 *\nFROM dbo.data;\n`);
        }
      } catch {
        setError("فشل في تحليل الملف.");
      } finally {
        setLoading(false);
      }
    },
    [onDataChange, publish],
  );

  // ─── Apply a shared/linked dataset ───
  const applyLinkedData = useCallback(
    (ds: LinkedDataset) => {
      setHeaders(ds.headers);
      setRows(ds.rows);
      setFileName(ds.fileName);
      setResult(null);
      setError("");
      setQuery(`SELECT TOP 100 *\nFROM dbo.data;\n`);
      publish({
        headers: ds.headers,
        rows: ds.rows,
        fileName: ds.fileName,
        source: "sql",
      });
      rememberProject({
        fileName: ds.fileName,
        rows: ds.rows.length,
        headers: ds.headers,
      });
      rememberAction(ds.fileName, {
        type: "sql",
        detail: "linked data loaded into SQL viewer",
        at: Date.now(),
      });
    },
    [publish],
  );

  // ─── Run query ───
  const runQuery = useCallback(
    (sqlText?: string) => {
      const sql = (sqlText ?? query).trim();
      if (!sql || rows.length === 0) return;
      const startTime = performance.now();
      setRunning(true);
      setError("");
      setResult(null);
      try {
        // Parse SELECT col1, col2 FROM data [WHERE ...] [GROUP BY c] [ORDER BY c] [LIMIT n] [TOP n]
        const selectMatch = sql
          .replace(/;;/g, ";")
          .match(/SELECT\s+(TOP\s+\d+\s+)?(.+?)\s+FROM\s+/i);
        if (!selectMatch)
          throw new Error("SELECT ... FROM مطلوب (لا ندعم DML التعديل)");
        const topN = selectMatch[1]
          ? Number(selectMatch[1].replace(/TOP\s+/i, "").trim())
          : 0;
        let exprs = selectMatch[2].trim();
        const rest = sql.slice(sql.indexOf("FROM") + 4);

        // ORDER BY
        let orderCol = "";
        let orderDesc = false;
        const orderMatch = rest.match(
          /ORDER\s+BY\s+(.+?)(?:\s+(ASC|DESC))?(?:;|$)/i,
        );
        let body = rest;
        if (orderMatch) {
          orderCol = orderMatch[1]
            .trim()
            .replace(/^\[|\]$/g, "")
            .replace(/^"|"$/g, "")
            .replace(/^`|`$/g, "");
          orderDesc = (orderMatch[2] || "").toUpperCase() === "DESC";
          body = body.slice(0, body.indexOf(orderMatch[0]));
        }

        // GROUP BY
        let groupCol = "";
        const groupMatch = body.match(
          /GROUP\s+BY\s+(.+?)(?:\s+ORDER\s+BY|\s+LIMIT|$)/i,
        );
        if (groupMatch) {
          groupCol = groupMatch[1]
            .trim()
            .replace(/^\[|\]$/g, "")
            .replace(/^"|"$/g, "")
            .replace(/^`|`$/g, "");
          body = body.slice(0, body.indexOf(groupMatch[0]));
        }

        // WHERE
        let whereClause = "";
        const whereMatch = body.match(
          /WHERE\s+(.+?)(?:\s+GROUP\s+BY|\s+ORDER\s+BY|\s+LIMIT|$)/i,
        );
        if (whereMatch) whereClause = whereMatch[1].trim();

        // LIMIT
        let limit = 1000;
        const limitMatch = body.match(/LIMIT\s+(\d+)/i);
        if (limitMatch) limit = Math.min(Number(limitMatch[1]), 5000);

        const rowMatches = (r: Record<string, unknown>): boolean => {
          if (!whereClause) return true;
          const evalOr = (orParts: string[][]): boolean =>
            orParts.some(evalAnd);
          const evalAnd = (andParts: string[]): boolean =>
            andParts.every(evalPrimitive);
          const evalPrimitive = (expr: string): boolean => {
            expr = expr.trim();
            const m = expr.match(
              /^\[?([\w.\u0600-\u06FF]+)\]?\s*(=|!=|<>|>=|<=|>|<|LIKE)\s*(.+)$/i,
            );
            if (!m) return true;
            const col = m[1]
              .replace(/^\[|\]$/g, "")
              .replace(/^"|"$/g, "")
              .replace(/^`|`$/g, "");
            const op = m[2].toUpperCase();
            const raw = m[3].trim();
            const cell =
              r[col] == null || r[col] === "" ? null : String(r[col]);
            if (cell === null) {
              if (raw.toUpperCase() === "NULL")
                return op === "=" || op === "IS";
              return op === "IS" && raw.toUpperCase() === "NULL" ? false : true;
            }
            if (raw.toUpperCase() === "NULL") {
              if (op === "IS") return true;
              if (op === "=") return false;
              return true;
            }
            const isStr =
              (raw.startsWith("'") && raw.endsWith("'")) ||
              (raw.startsWith('"') && raw.endsWith('"')) ||
              (raw.startsWith("N'") && raw.endsWith("'"));
            const val = isStr
              ? raw.replace(/^N?'|'$/g, "").replace(/^"|"$/g, "")
              : raw;
            if (op === "LIKE") {
              const needle = val
                .replace(/%/g, ".*")
                .replace(/_/g, ".")
                .toLowerCase();
              try {
                return new RegExp(`^${needle}$`).test(cell.toLowerCase());
              } catch {
                return false;
              }
            }
            if (!isStr) {
              const left = Number(cell);
              const right = Number(val);
              if (!Number.isNaN(left) && !Number.isNaN(right)) {
                switch (op) {
                  case "=":
                    return left === right;
                  case "!=":
                  case "<>":
                    return left !== right;
                  case ">":
                    return left > right;
                  case "<":
                    return left < right;
                  case ">=":
                    return left >= right;
                  case "<=":
                    return left <= right;
                }
              }
            }
            switch (op) {
              case "=":
                return cell === val;
              case "!=":
              case "<>":
                return cell !== val;
              case ">":
                return cell > val;
              case "<":
                return cell < val;
              case ">=":
                return cell >= val;
              case "<=":
                return cell <= val;
            }
            return true;
          };
          return evalOr(
            whereClause.split(/\s+OR\s+/).map((p) => p.split(/\s+AND\s+/)),
          );
        };

        // COUNT(*) special: if (COUNT(*) detected), treat as single-entry result
        const countAllMatch = sql.match(/COUNT\s*\(\s*\*\s*\)/i);
        if (countAllMatch && !selectMatch[1]) {
          const filteredAll = rows.filter(rowMatches);
          const el = performance.now() - startTime;
          setResult({
            columns: ["count"],
            rows: [{ count: filteredAll.length }],
            elapsedMs: Math.round(el * 100) / 100,
            rowCount: 1,
          });
          setHistory((prev) =>
            [
              {
                time: new Date().toLocaleTimeString(),
                query: sql,
                status: "ok" as const,
              },
              ...prev,
            ].slice(0, 10),
          );
          setRunning(false);
          return;
        }

        let filtered = rows.filter(rowMatches);

        // TOP N
        if (topN > 0) limit = Math.min(topN, 5000);

        // PROJECTION
        let outCols: string[] = [];
        let outRows: Record<string, unknown>[] = [];

        const isAggExpr = (e: string) =>
          /^(COUNT|SUM|AVG|MIN|MAX)\s*\(/i.test(e.trim());

        if (groupCol) {
          const aggExprs = exprs
            .split(",")
            .map((s) => s.trim())
            .filter(isAggExpr);
          if (!aggExprs.length)
            throw new Error("GROUP BY يتطلب دوال تجميع (COUNT/SUM/AVG/...)");
          const groups = new Map<string, Record<string, unknown>[]>();
          for (const r of filtered) {
            const key = String(r[groupCol] ?? "N/A");
            const arr = groups.get(key) || [];
            arr.push(r);
            groups.set(key, arr);
          }
          const computeAgg = (
            expr: string,
            groupRows: Record<string, unknown>[],
          ): unknown => {
            const mm = expr.match(
              /^(COUNT|SUM|AVG|MIN|MAX)\s*\(\s*([\w\[.\"\u0600-\u06FF*]+)\s*\)/i,
            );
            if (!mm) return null;
            const fn = mm[1].toUpperCase();
            const argCol = mm[2]
              .replace(/^\[|\]$/g, "")
              .replace(/^"|"$/g, "")
              .replace(/^`|`$/g, "");
            if (fn === "COUNT") return groupRows.length;
            const nums = groupRows
              .map((r) => Number(r[argCol]))
              .filter((n) => !Number.isNaN(n));
            if (!nums.length) return null;
            switch (fn) {
              case "SUM":
                return nums.reduce((a, b) => a + b, 0);
              case "AVG":
                return (
                  Math.round(
                    (nums.reduce((a, b) => a + b, 0) / nums.length) * 100,
                  ) / 100
                );
              case "MIN":
                return Math.min(...nums);
              case "MAX":
                return Math.max(...nums);
            }
            return null;
          };
          outCols = [
            groupCol,
            ...aggExprs.map((e, i) => {
              const am = e.match(/AS\s+\[?([\w.\u0600-\u06FF]+)\]?/i);
              return am ? am[1] : `agg_${i + 1}`;
            }),
          ];
          outRows = Array.from(groups.entries()).map(([key, grpRows]) => {
            const row: Record<string, unknown> = { [groupCol]: key };
            aggExprs.forEach((e, i) => {
              const am = e.match(/AS\s+\[?([\w.\u0600-\u06FF]+)\]?/i);
              row[am ? am[1] : `agg_${i + 1}`] = computeAgg(e, grpRows);
            });
            return row;
          });
        } else {
          const selParts = exprs
            .trim()
            .split(",")
            .map((s) => s.trim())
            .filter(Boolean);
          if (selParts.length === 1 && selParts[0] === "*") {
            outCols = headers;
            outRows = filtered;
          } else if (selParts.every(isAggExpr)) {
            outCols = selParts.map((e, i) => {
              const am = e.match(/AS\s+\[?([\w.\u0600-\u06FF]+)\]?/i);
              return am ? am[1] : `agg_${i + 1}`;
            });
            const computeAgg = (expr: string): unknown => {
              const mm = expr.match(
                /^(COUNT|SUM|AVG|MIN|MAX)\s*\(\s*([\w\[.\"\u0600-\u06FF*]+)\s*\)/i,
              );
              if (!mm) return null;
              const fn = mm[1].toUpperCase();
              const argCol = mm[2]
                .replace(/^\[|\]$/g, "")
                .replace(/^"|"$/g, "")
                .replace(/^`|`$/g, "");
              if (fn === "COUNT") return filtered.length;
              const nums = filtered
                .map((r) => Number(r[argCol]))
                .filter((n) => !Number.isNaN(n));
              if (!nums.length) return null;
              switch (fn) {
                case "SUM":
                  return nums.reduce((a, b) => a + b, 0);
                case "AVG":
                  return (
                    Math.round(
                      (nums.reduce((a, b) => a + b, 0) / nums.length) * 100,
                    ) / 100
                  );
                case "MIN":
                  return Math.min(...nums);
                case "MAX":
                  return Math.max(...nums);
              }
              return null;
            };
            const row: Record<string, unknown> = {};
            selParts.forEach((e, i) => {
              const am = e.match(/AS\s+\[?([\w.\u0600-\u06FF]+)\]?/i);
              row[am ? am[1] : `agg_${i + 1}`] = computeAgg(e);
            });
            outCols = Object.keys(row);
            outRows = [row];
          } else {
            outCols = selParts.map((e) => {
              const am = e.match(/AS\s+\[?([\w.\u0600-\u06FF]+)\]?/i);
              return am
                ? am[1]
                : e
                    .replace(/^\[|\]$/g, "")
                    .replace(/^"|"$/g, "")
                    .replace(/^`|`$/g, "")
                    .trim();
            });
            outRows = filtered.map((r) => {
              const row: Record<string, unknown> = {};
              selParts.forEach((e, i) => {
                const base = e.includes(" AS ") ? e.split(/\s+AS\s+/i)[0] : e;
                const colName = base
                  .replace(/^\[|\]$/g, "")
                  .replace(/^"|"$/g, "")
                  .replace(/^`|`$/g, "")
                  .trim();
                row[outCols[i]] = r[colName] ?? null;
              });
              return row;
            });
          }
        }

        // ORDER BY
        if (orderCol && outRows.length) {
          const f = orderDesc ? -1 : 1;
          outRows.sort((a, b) => {
            const av = a[orderCol];
            const bv = b[orderCol];
            if (av == null && bv == null) return 0;
            if (av == null) return 1;
            if (bv == null) return -1;
            const na = Number(av);
            const nb = Number(bv);
            if (!Number.isNaN(na) && !Number.isNaN(nb)) return (na - nb) * f;
            return String(av).localeCompare(String(bv)) * f;
          });
        }

        outRows = outRows.slice(0, limit);
        const elapsed = performance.now() - startTime;

        setResult({
          columns: outCols.length ? outCols : headers,
          rows: outRows,
          elapsedMs: Math.round(elapsed * 100) / 100,
          rowCount: outRows.length,
        });
        setHistory((prev) =>
          [
            {
              time: new Date().toLocaleTimeString(),
              query: sql,
              status: "ok" as const,
            },
            ...prev,
          ].slice(0, 10),
        );
      } catch (e) {
        const msg = e instanceof Error ? e.message : String(e);
        setError(msg);
        setHistory((prev) =>
          [
            {
              time: new Date().toLocaleTimeString(),
              query: sql,
              status: "error" as const,
            },
            ...prev,
          ].slice(0, 10),
        );
      } finally {
        setRunning(false);
      }
    },
    [query, rows, headers],
  );

  // ─── Export ───
  const exportResultCsv = () => {
    if (!result) return;
    const csv = Papa.unparse(result.rows, { columns: result.columns });
    dlStr(
      csv,
      `${(fileName || "data").replace(/\.[^.]+$/, "")}_query_result.csv`,
      "text/csv;charset=utf-8",
    );
  };
  const exportResultJson = () => {
    if (!result) return;
    dlStr(
      JSON.stringify(result.rows, null, 2),
      `${(fileName || "data").replace(/\.[^.]+$/, "")}_query_result.json`,
      "application/json",
    );
  };
  const copyQuery = () => {
    navigator.clipboard.writeText(query);
  };
  const saveQuery = () => {
    const queries = JSON.parse(localStorage.getItem("oqzaro:queries") || "[]");
    queries.push({
      name: `Query ${queries.length + 1}`,
      sql: query,
      time: Date.now(),
    });
    localStorage.setItem("oqzaro:queries", JSON.stringify(queries.slice(-20)));
  };

  // Schema tab
  const schemaSql = useMemo(() => {
    if (rows.length === 0) return "";
    const tableName = (fileName || "data")
      .replace(/[^\w\u0600-\u06FF]/g, "_")
      .replace(/\.[^.]+$/, "");
    let sql = makeCreateTable(tableName, headers, rows);
    sql += "\n\n-- Sample INSERT statements:\n";
    sql += makeInsertSql(tableName, headers, rows, 10);
    return sql;
  }, [rows, headers, fileName]);

  // Column null counts for schema view
  const columnInfo = useMemo(
    () =>
      headers.map((h) => ({
        name: h,
        type: detectSqlType(rows, h),
        nulls: rows.filter((r) => r[h] == null || r[h] === "").length,
        unique: new Set(rows.slice(0, 200).map((r) => String(r[h] ?? ""))).size,
      })),
    [headers, rows],
  );

  // ═══ RENDER ═══
  if (rows.length === 0) {
    return (
      <div className="border border-white/10 rounded-3xl bg-white/[0.02] p-5">
        <div className="flex items-center gap-3 mb-4">
          <div className="w-10 h-10 rounded-xl bg-gradient-to-br from-[#a91d22] to-[#e05a60] flex items-center justify-center shrink-0 shadow-lg shadow-red-500/20">
            <Database className="w-5 h-5 text-white" />
          </div>
          <div>
            <h2 className="font-semibold flex items-center gap-2">
              <span className="text-[#e05a60]">SQL Server</span> محرر
              الاستعلامات
            </h2>
            <p className="text-xs text-white/50">
              افتح ملفاً لتشغيل استعلامات SQL عليه (يدعم SELECT, WHERE, GROUP
              BY)
            </p>
          </div>
        </div>
        <div
          className="border-2 border-dashed border-[#a91d22]/40 rounded-2xl p-8 text-center cursor-pointer hover:bg-[#a91d22]/5 transition"
          onClick={() => inputRef.current?.click()}
        >
          <input
            ref={inputRef}
            type="file"
            accept=".csv,.xlsx,.xls"
            className="hidden"
            onChange={(e) => loadFile(e.target.files?.[0] || null)}
          />
          <Database className="h-12 w-12 text-[#e05a60] mx-auto mb-3" />
          <p className="font-medium">اسحب ملفك هنا أو انقر للاختيار</p>
          <p className="text-sm text-white/40 mt-1">يدعم CSV, XLSX, XLS</p>
        </div>
        <div className="mt-4 flex items-center gap-3 flex-wrap">
          <UseLinkedData onApply={applyLinkedData} />
        </div>
        {loading && (
          <div className="mt-4 flex items-center justify-center gap-2 text-[#e05a60]">
            <Loader2 className="w-5 h-5 animate-spin" /> جاري التحميل...
          </div>
        )}
        {error && (
          <div className="mt-4 bg-red-500/10 border border-red-500/30 text-red-400 text-sm px-4 py-3 rounded-2xl">
            {error}
          </div>
        )}
      </div>
    );
  }

  return (
    <div className="border border-white/10 rounded-3xl bg-white/[0.02] overflow-hidden">
      {/* ── Ribbon / Top Bar ── */}
      <div className="flex items-center gap-2 px-3 py-2 border-b border-white/10 bg-[#0d1420]">
        <div className="w-7 h-7 rounded-lg bg-gradient-to-br from-[#a91d22] to-[#e05a60] flex items-center justify-center shrink-0">
          <Database className="w-3.5 h-3.5 text-white" />
        </div>
        <span className="text-xs font-semibold text-white/80">
          SQLQuery1.sql
        </span>
        <span className="text-[10px] text-white/30">{fileName}</span>
        <div className="flex-1" />
        <div className="flex items-center gap-1">
          {PRESET_QUERIES.map((q) => (
            <button
              key={q.id}
              onClick={() => {
                setQuery(q.sql);
                setTab("query");
              }}
              className="text-[10px] px-2 py-1 rounded-lg bg-white/5 border border-white/10 text-white/50 hover:text-white hover:bg-white/10 transition"
            >
              {q.label}
            </button>
          ))}
        </div>
        <button
          onClick={() => inputRef.current?.click()}
          className="text-[11px] flex items-center gap-1 px-2.5 py-1.5 rounded-lg bg-white/5 border border-white/10 text-white/60 hover:text-white transition"
        >
          <UploadCloud className="w-3 h-3" /> فتح ملف
        </button>
        <input
          ref={inputRef}
          type="file"
          accept=".csv,.xlsx,.xls"
          className="hidden"
          onChange={(e) => {
            loadFile(e.target.files?.[0] || null);
            e.target.value = "";
          }}
        />
      </div>

      {/* ── Tabs ── */}
      <div className="flex items-center gap-1 px-3 pt-2 border-b border-white/10">
        {(
          [
            { id: "query", label: "استعلام", icon: FileCode },
            { id: "schema", label: "مخطط (DDL)", icon: Braces },
            { id: "data", label: "البيانات", icon: Table2 },
          ] as const
        ).map((t) => (
          <button
            key={t.id}
            onClick={() => setTab(t.id)}
            className={`text-[11px] flex items-center gap-1.5 px-3 py-2 rounded-t-lg transition border-x border-t ${tab === t.id ? "bg-white/[0.03] text-[#e05a60] border-white/10" : "text-white/40 hover:text-white/60 border-transparent"}`}
          >
            <t.icon className="w-3.5 h-3.5" /> {t.label}
          </button>
        ))}
      </div>

      {error && (
        <div className="mx-3 mt-2 bg-red-500/10 border border-red-500/30 text-red-400 text-xs px-3 py-2 rounded-lg">
          {error}
          <button onClick={() => setError("")} className="float-right">
            <X className="w-3 h-3" />
          </button>
        </div>
      )}

      {/* ── QUERY TAB ── */}
      {tab === "query" && (
        <div className="flex" style={{ minHeight: "480px" }}>
          {/* Object Explorer */}
          {objectExplorerOpen && (
            <div className="w-52 border-r border-white/10 p-2 hidden md:block">
              <div className="flex items-center justify-between px-2 py-1.5">
                <span className="text-[10px] font-bold text-white/50 tracking-wide">
                  مستكشف الكائنات
                </span>
                <button onClick={() => setObjectExplorerOpen(false)}>
                  <X className="w-3 h-3 text-white/30" />
                </button>
              </div>
              <div className="text-[11px] space-y-1 mt-1">
                <div className="flex items-center gap-1.5 text-[#e05a60] font-medium">
                  <Server className="w-3 h-3" /> localhost
                </div>
                <div className="flex items-center gap-1.5 text-white/50 pl-4">
                  <FolderTree className="w-3 h-3" /> قاعدة البيانات
                </div>
                <div className="flex items-center gap-1.5 text-white/50 pl-4">
                  <FolderTree className="w-3 h-3" /> الأمان
                </div>
                <button
                  onClick={() => setSchemaOpen((v) => !v)}
                  className="flex items-center gap-1.5 text-white/50 pl-4 hover:text-white/80"
                >
                  {schemaOpen ? (
                    <ChevronDown className="w-3 h-3" />
                  ) : (
                    <ChevronRight className="w-3 h-3" />
                  )}
                  <FolderTree className="w-3 h-3" /> الجداول
                </button>
                {schemaOpen && (
                  <div className="pl-8 space-y-0.5 mt-0.5">
                    <div
                      onClick={() => {
                        setTab("data");
                      }}
                      className="flex items-center gap-1 text-[#4f7cff] hover:bg-white/5 rounded px-1 cursor-pointer py-0.5"
                    >
                      <Table2 className="w-3 h-3" /> dbo.data
                    </div>
                    <div className="text-white/30 pl-4">
                      {headers.length} عمود
                    </div>
                  </div>
                )}
                <div className="flex items-center gap-1.5 text-white/50 pl-4">
                  <FolderTree className="w-3 h-3" /> طرق العرض
                </div>
                <div className="flex items-center gap-1.5 text-white/50 pl-4">
                  <FolderTree className="w-3 h-3" /> الإجراءات
                </div>
              </div>
            </div>
          )}
          {!objectExplorerOpen && (
            <button
              onClick={() => setObjectExplorerOpen(true)}
              className="w-6 border-r border-white/10 text-white/30 hover:text-white/60 flex items-center justify-center"
            >
              <ChevronRight className="w-3 h-3" />
            </button>
          )}

          {/* Editor + Results */}
          <div className="flex-1 min-w-0">
            {/* SQL Editor */}
            <div className="relative">
              <div className="flex items-center justify-between px-3 py-1.5 border-b border-white/5">
                <span className="text-[10px] text-white/30">محرر SQL</span>
                <div className="flex items-center gap-1">
                  <button
                    onClick={copyQuery}
                    className="p-1 rounded hover:bg-white/10"
                  >
                    <Copy className="w-3 h-3 text-white/40" />
                  </button>
                  <button
                    onClick={saveQuery}
                    className="p-1 rounded hover:bg-white/10"
                    title="حفظ الاستعلام"
                  >
                    <Save className="w-3 h-3 text-white/40" />
                  </button>
                  <button
                    onClick={() => runQuery()}
                    disabled={running || rows.length === 0}
                    className="flex items-center gap-1.5 text-[11px] bg-gradient-to-r from-[#a91d22] to-[#e05a60] text-white font-medium px-3 py-1 rounded-lg hover:brightness-110 disabled:opacity-40 ml-1"
                  >
                    {running ? (
                      <Loader2 className="w-3 h-3 animate-spin" />
                    ) : (
                      <Play className="w-3 h-3" />
                    )}
                    تنفيذ
                  </button>
                </div>
              </div>
              {/* Overlay for syntax highlighting */}
              <div className="relative">
                <pre
                  className="m-0 px-4 py-3 font-mono text-[12px] leading-5 text-transparent whitespace-pre-wrap bg-[#0a1428] overflow-y-auto"
                  style={{ maxHeight: "240px", minHeight: "140px" }}
                  dir="ltr"
                  aria-hidden
                >
                  {highlightSql(query + "\n")}
                </pre>
                <textarea
                  value={query}
                  onChange={(e) => setQuery(e.target.value)}
                  onKeyDown={(e) => {
                    if (e.key === "F5") {
                      e.preventDefault();
                      runQuery();
                    }
                    if (e.key === "Enter" && e.ctrlKey) {
                      e.preventDefault();
                      runQuery();
                    }
                  }}
                  spellCheck={false}
                  dir="ltr"
                  className="absolute inset-0 w-full h-full p-0 px-4 py-3 font-mono text-[12px] leading-5 bg-transparent text-[#a5f3fc] placeholder-white/20 outline-none resize-none caret-[#e05a60] whitespace-pre-wrap break-words overflow-y-auto"
                  style={{ maxHeight: "240px", minHeight: "140px" }}
                />
              </div>
              <p className="text-[10px] text-white/25 px-3 pb-1">
                F5 أو Ctrl+Enter للتنفيذ · يدعم: SELECT, WHERE, GROUP BY, ORDER
                BY, LIMIT, COUNT, SUM, AVG, MIN, MAX
              </p>
            </div>

            {/* Results */}
            <div className="border-t border-white/10">
              <div className="flex items-center justify-between px-3 py-1.5">
                <span className="text-[10px] text-white/30">
                  {result ? (
                    <>
                      <CheckCircle2 className="w-3 h-3 inline text-emerald-400 mr-1" />
                      نجح — {result.rowCount} صف · {result.elapsedMs}ms
                    </>
                  ) : (
                    "النتائج"
                  )}
                </span>
                {result && (
                  <div className="flex items-center gap-1">
                    <button
                      onClick={exportResultCsv}
                      className="text-[10px] flex items-center gap-1 px-2 py-1 rounded bg-white/5 border border-white/10 text-white/50 hover:text-white"
                    >
                      <Download className="w-2.5 h-2.5" /> CSV
                    </button>
                    <button
                      onClick={exportResultJson}
                      className="text-[10px] flex items-center gap-1 px-2 py-1 rounded bg-white/5 border border-white/10 text-white/50 hover:text-white"
                    >
                      <Download className="w-2.5 h-2.5" /> JSON
                    </button>
                  </div>
                )}
              </div>
              {result && (
                <div className="overflow-auto max-h-[260px]">
                  <table className="w-full text-[11px]">
                    <thead className="sticky top-0 z-10">
                      <tr>
                        <th className="px-2 py-1.5 bg-[#a91d22]/20 text-white/60 font-medium border-b border-white/10 text-left whitespace-nowrap">
                          #
                        </th>
                        {result.columns.map((c) => (
                          <th
                            key={c}
                            className="px-2 py-1.5 bg-[#a91d22]/20 text-white/60 font-medium border-b border-white/10 text-left whitespace-nowrap"
                          >
                            {c}
                          </th>
                        ))}
                      </tr>
                    </thead>
                    <tbody>
                      {result.rows.map((r, i) => (
                        <tr
                          key={i}
                          className="border-b border-white/5 hover:bg-white/[0.02]"
                        >
                          <td className="px-2 py-1 text-white/30">{i + 1}</td>
                          {result.columns.map((c) => (
                            <td
                              key={c}
                              className="px-2 py-1 text-white/70 whitespace-nowrap max-w-[200px] truncate"
                            >
                              {r[c] == null || r[c] === "" ? (
                                <span className="text-red-400/50 italic">
                                  NULL
                                </span>
                              ) : (
                                String(r[c])
                              )}
                            </td>
                          ))}
                        </tr>
                      ))}
                    </tbody>
                  </table>
                  {result.rows.length === 0 && (
                    <p className="text-center text-white/30 text-xs py-6">
                      لا توجد نتائج
                    </p>
                  )}
                </div>
              )}
            </div>
          </div>
        </div>
      )}

      {/* ── SCHEMA TAB ── */}
      {tab === "schema" && (
        <div className="p-4 grid grid-cols-1 lg:grid-cols-2 gap-4">
          <div>
            <div className="flex items-center justify-between mb-2">
              <h3 className="text-xs font-semibold text-white/60 flex items-center gap-2">
                <Braces className="w-4 h-4 text-[#e05a60]" /> مخطط الجدول (DDL)
              </h3>
              <button
                onClick={() =>
                  dlStr(
                    schemaSql,
                    `${(fileName || "data").replace(/\.[^.]+$/, "")}_schema.sql`,
                  )
                }
                className="text-[10px] flex items-center gap-1 px-2 py-1 rounded bg-white/5 border border-white/10 text-white/50 hover:text-white"
              >
                <Download className="w-2.5 h-2.5" /> تنزيل SQL
              </button>
            </div>
            <pre
              className="bg-[#0a1428] border border-white/10 rounded-xl p-4 text-[11px] leading-5 text-[#7dd3fc] overflow-auto max-h-[440px] font-mono whitespace-pre"
              dir="ltr"
            >
              {highlightSql(schemaSql)}
            </pre>
          </div>
          <div>
            <h3 className="text-xs font-semibold text-white/60 mb-2 flex items-center gap-2">
              <Columns3 className="w-4 h-4 text-[#4f7cff]" /> الأعمدة (
              {columnInfo.length})
            </h3>
            <div className="overflow-auto rounded-xl border border-white/10 max-h-[440px]">
              <table className="w-full text-[11px]">
                <thead className="sticky top-0 z-10">
                  <tr>
                    <th className="px-3 py-2 bg-[#0a1428] text-white/60 font-medium border-b border-white/10 text-left">
                      العمود
                    </th>
                    <th className="px-3 py-2 bg-[#0a1428] text-white/60 font-medium border-b border-white/10 text-left">
                      النوع
                    </th>
                    <th className="px-3 py-2 bg-[#0a1428] text-white/60 font-medium border-b border-white/10 text-left">
                      فارغ
                    </th>
                    <th className="px-3 py-2 bg-[#0a1428] text-white/60 font-medium border-b border-white/10 text-left">
                      فريد
                    </th>
                  </tr>
                </thead>
                <tbody>
                  {columnInfo.map((c) => (
                    <tr
                      key={c.name}
                      className="border-b border-white/5 hover:bg-white/[0.02]"
                    >
                      <td className="px-3 py-1.5 text-white/80 font-medium whitespace-nowrap">
                        {c.name}
                      </td>
                      <td className="px-3 py-1.5">
                        <span className="text-[9px] bg-[#a91d22]/10 text-[#e05a60] border border-[#a91d22]/30 rounded-full px-2 py-0.5">
                          {c.type}
                        </span>
                      </td>
                      <td className="px-3 py-1.5 text-white/50">{c.nulls}</td>
                      <td className="px-3 py-1.5 text-white/50">{c.unique}</td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          </div>
        </div>
      )}

      {/* ── DATA TAB ── */}
      {tab === "data" && (
        <div className="p-3">
          <div className="flex items-center gap-2 mb-2">
            <Table2 className="w-4 h-4 text-[#4f7cff]" />
            <span className="text-xs text-white/60 font-medium">
              dbo.data — {rows.length} صف
            </span>
            <div className="flex-1" />
            <button
              onClick={() => setQuery(`SELECT TOP 100 *\nFROM dbo.data;\n`)}
              className="text-[10px] px-2 py-1 rounded bg-white/5 border border-white/10 text-white/50 hover:text-white"
            >
              استعلام كامل
            </button>
          </div>
          <div className="overflow-auto rounded-xl border border-white/10 max-h-[440px]">
            <table className="w-full text-[11px]">
              <thead className="sticky top-0 z-10">
                <tr>
                  <th className="px-2 py-1.5 bg-[#0a1428] text-white/60 font-medium border-b border-white/10 text-left whitespace-nowrap">
                    #
                  </th>
                  {headers.map((h) => (
                    <th
                      key={h}
                      className="px-2 py-1.5 bg-[#0a1428] text-white/60 font-medium border-b border-white/10 text-left whitespace-nowrap"
                    >
                      {h}
                    </th>
                  ))}
                </tr>
              </thead>
              <tbody>
                {rows.slice(0, 200).map((r, i) => (
                  <tr
                    key={i}
                    className="border-b border-white/5 hover:bg-white/[0.02]"
                  >
                    <td className="px-2 py-1 text-white/30">{i + 1}</td>
                    {headers.map((h) => (
                      <td
                        key={h}
                        className="px-2 py-1 text-white/70 whitespace-nowrap max-w-[200px] truncate"
                      >
                        {r[h] == null || r[h] === "" ? (
                          <span className="text-red-400/50 italic">NULL</span>
                        ) : (
                          String(r[h])
                        )}
                      </td>
                    ))}
                  </tr>
                ))}
              </tbody>
            </table>
            {rows.length > 200 && (
              <p className="text-center text-white/30 text-xs py-3">
                يعرض أول 200 صف من {rows.length}. استخدم SQL لعرض المزيد.
              </p>
            )}
          </div>
        </div>
      )}

      {/* Query history */}
      {history.length > 0 && (
        <div className="border-t border-white/10 px-3 py-2">
          <div className="flex items-center gap-2 mb-1">
            <GitBranch className="w-3 h-3 text-white/30" />
            <span className="text-[10px] text-white/30">
              سجل الاستعلامات الأخيرة
            </span>
          </div>
          <div className="space-y-1">
            {history.slice(0, 5).map((h, i) => (
              <button
                key={i}
                onClick={() => {
                  setQuery(h.query);
                  setError("");
                }}
                className={`block w-full text-left text-[10px] px-2 py-1 rounded truncate font-mono ${h.status === "ok" ? "bg-white/[0.02] text-white/40 hover:text-white/70" : "bg-red-500/5 text-red-300/50 hover:text-red-300"}`}
                dir="ltr"
              >
                <span className="text-white/20 mr-2">{h.time}</span>
                {h.query.split("\n")[0].substring(0, 60)}
              </button>
            ))}
          </div>
        </div>
      )}
    </div>
  );
}
